name: ChunksRefresher
version: 0.0.8-SNAPSHOT-20211217-1
description: Plugin browsing through chunks of a map and loading them like if it was a player
author: Damien VERLYNDE
website: http://www.huvecraft.fr/
main: fr.huvecraft.plugins.chunksrefresher.ChunksRefresher
api-version: 1.13
database: false

commands:
  chunksrefresher:
    description: Refresh chunks of a world by loading them ; add "cancel" or "pause" to kill or suspend an operation
    aliases: chkref
    permission: chunksrefresher.use
    usage: "Usage: /chunksrefresher or /chkref <world> [create | cancel | pause | resume] [nomemcheck]"

permissions:
  chunksrefresher.use:
    description: Allow use of /chunksrefresher commands
    default: op