name: ChunksRefresher
version: 0.0.5-SNAPSHOT
description: Plugin browsing through chunks of a map and loading them like if it was a player
author: Damien VERLYNDE
website: http://www.huvecraft.fr/
main: fr.huvecraft.plugins.chunksrefresher.ChunksRefresher
api-version: 1.13
database: false

commands:
  chunksrefresher:
    description: Refresh chunks of a world by loading them
    aliases: chkref
    permission: chunksrefresher.use
    usage: "Usage: /chunksrefresher or /chkref [world]"

permissions:
  chunksrefresher.use:
    description: Allow use of /chunksrefresher commands
    default: op